name: full_web
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-154.0.dev

# Add regular dependencies here.
dependencies:
  web: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
